### ISSUE TITLE
"New from Recording" fails

### ISSUE THREAD

**Issue by rik-shaw** [wasta-linux/saymore-snap#3]
Maybe this is related to .wav not being supported, same error as #2 ??

```
Message (not an exception): There was a problem starting up volume monitoring.

Msg: NotEnabled calling waveInOpen
Class: NAudio.MmException
Source: NAudio
Assembly: NAudio, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null
Stack:    at NAudio.Wave.WaveIn.OpenWaveInDevice()
   at NAudio.Wave.WaveIn.StartRecording()
   at SIL.Media.Naudio.AudioRecorder.BeginMonitoringIfNeeded()
   at SIL.Media.Naudio.AudioRecorder.BeginMonitoring()
Thread: UI
Thread UI culture: en-US
Exception: NAudio.MmException
```

**Comment by n8marti** [comment]
Yes, I get this too. However this doesn't happen if a seemingly identical setup is created manually; i.e. use the same WINELOADER and WINETRICKS from the snap packages. Maybe there's some difference in how the audio devices get detected in the snap wine environment compared with the traditional wine environment? We're using devmode, so it can't be a confinement issue.
